// pipeline_fft.grpc_direct.pb.h
// Generated by protoc-gen-grpc-direct.  DO NOT EDIT.
//
// Source: pipeline_fft.proto
#pragma once

#include <memory>
#include <type_traits>
#include <vector>
#include <grpcpp/grpcpp.h>
#include "grpc_direct_types.h"
#include "pipeline_fft.pb.h"
#include "pipeline_fft.grpc.pb.h"

namespace pipeline_fft {

struct DirectBufferRequest;

// -------------------------------------------------------------------
// DirectBufferRequest
//
// Zero-copy companion for ::pipeline_fft::BufferRequest.
// -------------------------------------------------------------------
struct DirectBufferRequest : public ::grpc_direct::GDZCArrayReceiver {
    using InnerType = ::pipeline_fft::BufferRequest;

    ::pipeline_fft::BufferRequest inner;

    ::grpc_direct::ZCFloatArray samples;

    DirectBufferRequest() { samples._bind(inner.mutable_samples()); }
    DirectBufferRequest(const DirectBufferRequest& o)
        : inner(o.inner), hold_(o.hold_)
        { inner.mutable_samples()->_zcptr_ = o.inner.samples()._zcptr_; inner.mutable_samples()->_zcsz_  = o.inner.samples()._zcsz_; samples._bind(inner.mutable_samples()); }
    DirectBufferRequest(DirectBufferRequest&& o) noexcept
        : hold_(std::move(o.hold_)),
          _loan_handle(o._loan_handle), _response(o._response)
        { auto _zcp_samples = o.inner.samples()._zcptr_; auto _zcz_samples = o.inner.samples()._zcsz_; inner = std::move(o.inner); inner.mutable_samples()->_zcptr_ = _zcp_samples; inner.mutable_samples()->_zcsz_  = _zcz_samples; samples._bind(inner.mutable_samples()); o._loan_handle = nullptr; }
    DirectBufferRequest& operator=(const DirectBufferRequest& o) {
        inner = o.inner; hold_ = o.hold_;
        inner.mutable_samples()->_zcptr_ = o.inner.samples()._zcptr_; inner.mutable_samples()->_zcsz_  = o.inner.samples()._zcsz_; samples._bind(inner.mutable_samples()); return *this;
    }
    DirectBufferRequest& operator=(DirectBufferRequest&& o) noexcept {
        auto _zcp_samples = o.inner.samples()._zcptr_; auto _zcz_samples = o.inner.samples()._zcsz_;
        inner = std::move(o.inner); hold_ = std::move(o.hold_);
        _loan_handle = o._loan_handle; _response = o._response;
        inner.mutable_samples()->_zcptr_ = _zcp_samples; inner.mutable_samples()->_zcsz_  = _zcz_samples; samples._bind(inner.mutable_samples()); o._loan_handle = nullptr; return *this;
    }

    bool Prepare(::grpc::ServerContext* ctx);
    bool Send();
    void Prepare(::grpc::ServerContext* ctx, InnerType* response);
    void Finalize();

    void ParseGDZCArrays(const void* data, size_t size,
                         std::shared_ptr<::grpc_direct::BufferHandle> handle) override;

    ::grpc_direct::Span<const float> samples_span() const {
        if (inner.samples()._zcptr_) return { inner.samples()._zcptr_, inner.samples()._zcsz_ };
        const auto& rf = inner.samples().values();
        return {rf.data(), static_cast<size_t>(rf.size())};
    }

    static void _SetupStandardPath(InnerType& src, InnerType* dst);
    static void _CopyScalars(const InnerType& src, InnerType* dst);

private:
    std::shared_ptr<::grpc_direct::BufferHandle> hold_;
    GrpcDirectActiveRequest* _loan_handle = nullptr;
    InnerType*               _response    = nullptr;
};

} // namespace pipeline_fft

// ---------------------------------------------------------------------------
// Inline implementations
// ---------------------------------------------------------------------------
namespace pipeline_fft {

inline bool DirectBufferRequest::Prepare(::grpc::ServerContext* ctx) {
    _loan_handle = grpc_direct::GetActiveLoan(ctx);
    if (_loan_handle) return true;
    _SetupStandardPath(inner, &inner);
    return false;
}

inline bool DirectBufferRequest::Send() {
    if (!_loan_handle) return false;
    size_t _protoSize = inner.ByteSizeLong();
    uint8_t* _protoBuf = nullptr;
    if (_protoSize > 0) {
        _protoBuf = new uint8_t[_protoSize];
        inner.SerializeToArray(_protoBuf, static_cast<int>(_protoSize));
    }
    bool ok = grpc_direct_server_send_status(_loan_handle, GRPC_DIRECT_STATUS_OK, nullptr, _protoBuf, _protoSize) == 0;
    if (_protoBuf) delete[] _protoBuf;
    grpc_direct::MarkLoanSent();
    return ok;
}

inline void DirectBufferRequest::Prepare(::grpc::ServerContext* ctx, InnerType* response) {
    _response = response;
    _loan_handle = grpc_direct::GetActiveLoan(ctx);
    if (_loan_handle) return;
    _SetupStandardPath(inner, _response);
}

inline void DirectBufferRequest::_SetupStandardPath(InnerType& src, InnerType* dst) {
    dst->mutable_samples()->mutable_values()->Resize(static_cast<int>(src.mutable_samples()->_reserved), 0);
    src.mutable_samples()->_captured_ptr = dst->mutable_samples()->mutable_values()->mutable_data();
}

inline void DirectBufferRequest::Finalize() {
    if (_loan_handle) {
        size_t _protoSize = inner.ByteSizeLong();
        uint8_t* _protoBuf = nullptr;
        if (_protoSize > 0) {
            _protoBuf = new uint8_t[_protoSize];
            inner.SerializeToArray(_protoBuf, static_cast<int>(_protoSize));
        }
        grpc_direct_server_send_status(_loan_handle, GRPC_DIRECT_STATUS_OK, nullptr, _protoBuf, _protoSize);
        if (_protoBuf) delete[] _protoBuf;
        grpc_direct::MarkLoanSent();
    } else if (_response) {
        _CopyScalars(inner, _response);
    }
}

inline void DirectBufferRequest::_CopyScalars(const InnerType& src, InnerType* dst) {
    dst->set_send_timestamp_ns(src.send_timestamp_ns());
    dst->set_seq_num(src.seq_num());
    dst->set_raw_samples(src.raw_samples());
}

inline void DirectBufferRequest::ParseGDZCArrays(
    const void* data, size_t size,
    std::shared_ptr<::grpc_direct::BufferHandle> handle)
{
    hold_ = handle;
    inner.mutable_samples()->_zcptr_ = nullptr;
    inner.mutable_samples()->_zcsz_  = 0;
    ::grpc_direct::ScopedZCParseMode _zc;
    inner.ParseFromArray(data, static_cast<int>(size));
}

} // namespace pipeline_fft


namespace grpc_direct_registration {

template<typename T, typename = void>
struct _has_StreamBuffersPerMessage : std::false_type {};
template<typename T>
struct _has_StreamBuffersPerMessage<T, std::void_t<decltype(std::declval<T>().StreamBuffersPerMessage(
    std::declval<::grpc::ServerContext*>(),
    std::declval<const ::pipeline_fft::BufferRequest*>(),
    std::declval<::pipeline_fft::PipelineSummary*>()))>> : std::true_type {};

template<typename RouterT, typename ServiceT>
inline void InitPipelineFFTServiceGDZCRouter(RouterT& router, ServiceT* service) {
    static_assert(std::is_base_of<::pipeline_fft::PipelineFFTService::Service, ServiceT>::value,
        "InitPipelineFFTServiceGDZCRouter: ServiceT must derive from ::pipeline_fft::PipelineFFTService::Service");
    (void)service;

    // /pipeline_fft.PipelineFFTService/StreamBuffers (streaming)
    if constexpr (_has_StreamBuffersPerMessage<ServiceT>::value) {
        router.RegisterStreaming(
            "/pipeline_fft.PipelineFFTService/StreamBuffers",
            [service]() -> typename RouterT::StreamHandler {
                auto _state = std::make_shared<::pipeline_fft::PipelineSummary>();
                auto _req = std::make_shared<::pipeline_fft::BufferRequest>();
                return [service, _state, _req](const uint8_t* req, int reqLen,
                                         GrpcDirectActiveRequest* loanHandle) -> int {
                    if (reqLen > 0 && !_req->ParseFromArray(req, reqLen)) return -1;
                    ::grpc::ServerContext ctx;
                    auto status = service->StreamBuffersPerMessage(&ctx, _req.get(), _state.get());
                    if (!status.ok()) return 0;
                    size_t _protoSize = _state->ByteSizeLong();
                    uint8_t* _protoBuf = nullptr;
                    if (_protoSize > 0) {
                        _protoBuf = new uint8_t[_protoSize];
                        _state->SerializeToArray(_protoBuf, static_cast<int>(_protoSize));
                    }
                    int _rc = grpc_direct_server_send_status(loanHandle, GRPC_DIRECT_STATUS_OK, nullptr, _protoBuf, _protoSize);
                    if (_protoBuf) delete[] _protoBuf;
                    return _rc == 0 ? 1 : -1;
                };
            });
    }

}

} // namespace grpc_direct_registration
